### ISSUE TITLE
How should we manage the sumped surface subcatchments

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#169]
related issues #157, #132

Under the current system:
The surface subcatchments point to a node that is on the collection system (not the sump).
We flag the surface subcatchment as infiltration.
The surface subcatchments in in the trace.

In the model, We send the flow to infiltration.  We do not explicitly model the sumps themselves.

In the new system we could send the director to infiltration or to the sump.  In either case the street areas pointing to the sump would not be traced in.

__Options:__
direct to infiltration and allow these areas to not be traced
direct to infiltration and put a zero area director to a node that will be traced
use the overland flow destination field

 __[selected]__
If the subcatchment is sumped, create an infiltration director, and a zero area director to the alt_trace_manhole that is in the surface subcatchment

**Comment by arnelmandilag** [comment]
I am in favor of the zero area director option as it allows people to have a better sense of the intended model basin extent, but typing that director somehow so that 1) people know what it is immediately when they see it and 2) it allows validation to prevent it from ever having an area. I don't want to have too many "codified" sequences to represent a well-known object...EMGAATS 2 is full of those, and I think that's part of what confuses people.
