### ISSUE TITLE
To reopen model must have connection to folder containing geodatabase

### ISSUE THREAD

**Issue by yarrowm** [besasm/EMGAATS#209]
When reopening a saved model, can only open if there is a folder connection to the folder containing the model geodatabase. In other words, the dialog does not allow to view or open subfolders, only geodatabases. This can be worked around by connecting to each folder containing a model geodatabase, but as we work on more models, our folder connections are going to be very cluttered and adding all the folder connections should not be necessary. See example showing no subfolders in My Documents.
![image](https://cloud.githubusercontent.com/assets/16343206/12042294/7268606a-ae2e-11e5-9cab-043975449e16.png)

**Comment by arnelmandilag** [comment]
Collins and I talked about this before he left on Thursday and we will rework this so that we avoid using the ArcMap "open geodatabase" dialog and instead use the stock open directory dialog to find an existing model. The opening of the related file geodatabase housing the spatial and local model data will be hidden from the user.

Will be resolved in #184.

**Comment by ahedhi** [comment]
The current dialog should be showing subfolders. I think the My Documents folder is special because "My Documents" is just an alias now in Windows. You should connect to the "Documents" folder in your user folder instead.

If we implement what Arnel and Dave talked about, however, this is irrelevant.

**Comment by yarrowm** [comment]
Both responses are helpful. It is not possible to browse to the "documents" folder to connect. It had to be typed in. Now it works fine once connected to documents.

**Comment by collinsfoobar** [comment]
This is obsolete per #184
