### ISSUE TITLE
Area shape editing

### ISSUE THREAD

**Issue by yarrowm** [besasm/EMGAATS#229]
How are these area shapes going to be maintained?

**Comment by arnelmandilag** [comment]
Technicians will continue to change areas on an as-needed project basis using aerials and other methods. There is currently an exploratory effort to merge ASM's impervious area updates with other program updates, including those from Billing and Private Property Retrofit. This need actually points at a need in the bureau for a private property asset database that can somehow meet the requirements posed by our three (and possibly more) teams.

Technicians will be asked to provide an initial push to update these areas prior to the next System Plan update.

Collins has devised an initial import of MapInfo-based impervious areas containing the three main categories (ROW, parking, building), which may expand to include driveways but not sidewalks. Sidewalks are theorized to not be essentially effective when compared to monitoring data due to interception of water by parking strips. They may still be added on an as-needed basis for larger properties.

**Comment by yarrowm** [comment]
The question is whether editing will be done on an external database and results imported, or are we maintaining our area data directly in these tools?

**Comment by arnelmandilag** [comment]
The "gold" copy of areas will be on the server, and techs will have the ability to do both: edit externally or directly on the server. Modelers will only have the ability to edit these externally (after extracting a model and then modifying it), which they will then direct a technician to check and upload.
